### ISSUE TITLE
always installs dev dependencies

### ISSUE THREAD

**Issue by gilligan** [svanderburg/node2nix#72] opened 2018-01-02 10:58 UTC
node2nix seems to always install devDependencies even though by default they should not be installed

**steps to reproduce**
1. `npm init`
2. `npm install ramda --save`
3. `npm install lodash --save-dev`
4. `node2nix -8 -l ./package-lock.json`
4. `nix-build -A package`

**expected behavior**
In `./result/lib/node_modules/${project_name}/node_modules` there is one single folder: `ramda`, the only non-dev dependency.

**actual behavior**
In `./result/lib/node_modules/${project_name}/node_modules` there is `ramda` and `lodash` even though lodash is a devDependency which should not have been installed

--------

**package.json**
```
{
  "name": "node2nix-dev-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ramda": "^0.25.0"
  },
  "devDependencies": {
    "lodash": "^4.17.4"
  }
}
```

**package-lock.json**
```
{
  "name": "node2nix-dev-test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "lodash": {
      "version": "4.17.4",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz",
      "integrity": "sha1-eCA6TRwyiuHYbcpkYONptX9AVa4=",
      "dev": true
    },
    "ramda": {
      "version": "0.25.0",
      "resolved": "https://registry.npmjs.org/ramda/-/ramda-0.25.0.tgz",
      "integrity": "sha512-GXpfrYVPwx3K7RQ6aYT8KPS8XViSXUVJT1ONhoKPE9VAleW42YE+U+8VEyGWt41EnEQW7gwecYJriTI0pKoecQ=="
    }
  }
}
```

**Comment by gilligan** [comment] 2018-01-02 10:59
@svanderburg am I misunderstanding something again or is this a bug?

**Comment by svanderburg** [comment] 2018-01-02 15:57
Maybe I know what the problem is -- the lock file seems to include development dependencies, but you are doing a regular install.

It seems that the generator is not smart enough yet to figure out that the dev dependencies should be skipped. As a result, it will simply include all the dependencies that it sees in the lock file.

I have to make an adjustment to the generator to skip them if we don't generate Nix expressions in development mode.

**Comment by svanderburg** [comment] 2018-01-04 22:06
@gilligan I just made a fix for this in revision 56c093e32e01e41995b68d7d7d0f33812e55aa50

Can you install the development version and check if it works for you?

**Comment by gilligan** [comment] 2018-01-04 22:10
Cool, i will check it out tomorrow!

**Comment by svanderburg** [comment] 2018-01-18 20:42
I assume this problem can be considered fixed now.

**Closed by svanderburg** 2018-01-18 20:42 UTC

**Comment by yaitskov** [comment] 2021-03-22 21:34
Now devDependencies are ignored. What is canonical way to install them with nix then?

```
nix-shell -A shell --pure
npm install
```
???

**Comment by mikeplus64** [comment] 2021-03-27 01:50
> Now devDependencies are ignored. What is canonical way to install them with nix then?
> 
> ```
> nix-shell -A shell --pure
> npm install
> ```
> 
> ???

I think the `--development` option is what you need to include `devDependencies`. I dunno if it has other effects though; it might be good to have an explicit `--include-dev-dependencies` flag.
