### ISSUE TITLE
nix-shell unpacks every time

### ISSUE THREAD

**Issue by jedahu** [svanderburg/node2nix#74] opened 2018-01-29 21:18 UTC
Every time the shell is entered it seems half of the internet (thanks npm!) is unpacked:
```
unpacking source archive /nix/store/....
unpacking source archive /nix/store/....
unpacking source archive /nix/store/....
```
Followed by a lengthy: `pinpointing versions of dependencies...`

Is there any way to cache this output in the store? Or am I missing something?

**Comment by svanderburg** [comment] 2018-02-27 17:30
They will be cached in the store, but the problem is the composition process. Contrary to "ordinary" Nix packages, in Nix-NPM deployments, the package and all dependencies are composed in one single derivation.

Unfortunately, this is "necessary evil" to retain compatibility with NPM -- e.g. when we would symlink between store paths, NPM will always resolve the location of the dependency and look for relative paths from there, breaking a substantial number of packages. See this blog post for a more detailed explanation: http://sandervanderburg.blogspot.com/2016/02/managing-npm-flat-module-installations.html

I, however, may have an idea to reduce the sensitivity of the rebuilds. Currently the `shell` job will take the entire source directory as an input, but maybe I should change it so that it will only use `package.json`. This is something I need to investigate.

**Comment by wmertens** [comment] 2018-02-28 19:17
@svanderburg how about doing the same as the new v5.7 `npm ci` and only using `package-lock.json`? That already has all the dep info in an easy to parse format…

**Comment by svanderburg** [comment] 2018-03-12 13:13
@wmertens This is already what version 1.5.x can do -- if a repo includes a `package-lock.json` file then node2nix can use it, including the output hashes that the lock file contains. This makes the generation process a lot faster.

But it does not solve the "unpack slowness" problem -- whenever a dependency changes the builder needs to unpack all dependencies in one derivation. This is because the entire node_modules/ tree is statically included with every package that is built with node2nix. Not very nice, but necessary evil to ensure compatibility, for example with deduplicated node_modules/ trees.

**Comment by wmertens** [comment] 2018-03-12 20:35
@svanderburg Hmmm, doesn't node handle symlinks by resolving relative to the original files? So if each module in an app is packaged by symlinking all its dependencies as required by the app, then deps can just be symlinked?

E.g.

```
.
├── a/
│   └── index.js
├── b/
│   ├── index.js
│   └── node_modules/
│       └── a -> ../../a/
├── c/
│   ├── index.js
│   └── node_modules/
│       └── a -> ../../a/
├── index.js
└── node_modules/
    ├── a -> ../a/
    ├── b -> ../b/
    └── c -> ../c/
```

a/index.js:
```js
module.exports = {a: Math.random()}
```

b/index.js:
```js
const a = require('a')
module.exports = {b: Math.random(), a}
```

c/index.js
```js
const a = require('a')
module.exports = {c: Math.random(), a}
```

index.js
```js
console.log(require('c'), require('b'), require('a'))
```

```
$ node index.js
{ c: 0.24326151200878576, a: { a: 0.10645216658826184 } } { b: 0.5486160025848987, a: { a: 0.10645216658826184 } } { a: 0.10645216658826184 }
```

Or is that what you are doing already? I'm not actually using `node2nix` yet, I tried a long time ago but had a bunch of issues 😀

**Comment by wmertens** [comment] 2018-03-12 20:59
I re-read the blogpost you linked and it seems that the original approach you took is what I showed above, except that you didn't use the full resolved project dependencies? And then later you tried different approaches like pinning versions but cyclic deps broke that?

So, the real problem is: Given a project with deps a, b, c, d, e and cyclic dependencies (`[in brackets]`) between them like `a[b,c]; c[a,e]; d[b,a,e]`, and each having a specific version `1, 2, 3, 4, 5`, the required packages for the project would be `a1[b2[],c3[a1[cycle],e5[]]; c3[a1[...],e5[]]; d4[b2[],a[...],e5[]]`, right?

In this case, the cycling packages can only be built as a unit, but all the others can be built independently, no? In this case, we'd have the packages `b2`, `e5`, `a1+c3`, `d4`?

**Comment by jbboehr** [comment] 2018-06-01 00:17
What's the reason to not just store the unpacked `node_modules` in a `${package}-deps` derivation and symlink the whole thing in? It doesn't efficiently re-use packages between derivations, but it would at least save unpacking 'the whole world' every build. Does node have issues resolving symlinks in this case as well?

**Comment by wmertens** [comment] 2018-06-01 08:51
well, pnpm basically does the same, only somehow they manage to do it in a
few seconds.

**Comment by jbboehr** [comment] 2018-06-02 02:27
Would this solve the symlinking issues? https://nodejs.org/api/cli.html#cli_preserve_symlinks

**Comment by wmertens** [comment] 2018-06-05 19:35
It would cause some native modules to fail as mentioned there…

**Comment by baracoder** [comment] 2019-02-08 15:27
This issue is a bummer. I hoped to leverage the nix store to get rid of `npm install` in a CI script of an angular project, but this makes it really slow, especially because node-sass is rebuilt every time.

**Comment by hlolli** [comment] 2019-10-05 12:05
Using grpc (because of firebase) and I need to build it also every time, perhaps I can find a way to put that part in a seperate derivation and override it into the main package nodeEnv.

**Closed** 2020-11-05 20:10 UTC

**Comment by thomasjm** [comment] 2020-11-06 00:32
@svanderburg this issue should probably stay open, since #205 didn't address the most common workflows.

**Comment by irisjae** [comment] 2022-07-01 14:10
@svanderburg Having myself somewhat familiarised with the the node2nix code and the issues you've mentioned, I believe that it is possible to achieve a more Nix-like node packaging solution if we simply pinpointed all the dependencies upfront when generating the node-packages.nix, in a manner akin to content-addressing the dependencies of the output? Has this been considered by you already previously?

As far as I am aware, node2nix simply seems the better supported option for making node packages work today, compared to options like nix-npm-buildpackage and npmlock2nix; where those tools are broken due to npm issues (eg ENOTCACHED issues), node2nix remains working. However, the very long rebuild times from the incessant unpacking and pinpointing really begs to be addressed.

I am looking to perhaps make a patch (even if for only my usage) to 1) pinpoint dependencies upfront, and 2) thusly, separate the pinpointed dependencies into their own derivations (as I note you have previously done). I have also noticed the usage of readFileSync in the dependency pinpointing code, which can be much parallelised by using the async variant.

I would appreciate any advice from you on the approach I am planning.

**Comment by thomasjm** [comment] 2022-07-01 21:18
@irisjae you might want to just try the approach I mentioned in #205. I never tried using it outside of the use-case I was interested in, but it should work for most (all?) cases.

**Comment by irisjae** [comment] 2022-07-02 15:20
@thomasjm I'm not sure I understand you correctly - I see that the PR you referenced is already merged and I am working with a version of node2nix that seems to include it.

The approach I am exploring is to precompute the unpacking and dependency pinpointing steps, for every specific dependency (and its associated sub-dependency combination) in the node-packages.nix, into separate derivations - so that having built the node2nix derivation of a package.json once, thereafter, modified node2nix derivations (from modifying package.json) can reuse most of the unchanged dependencies.

**Comment by thomasjm** [comment] 2022-07-02 22:47
Right, I'm saying you might not need to do all that if you adopt the approach I used in #205 to your use-case.

I was interested in building the `nodeDependencies` derivation from `node-packages.nix`. The reason it kept unpacking is because the derivation depended on all the files in my project, so a change to any of them resulting in re-realizing that derivation. The fix was to make `nodeDependencies` only depend on `package.json`/`package-lock.json` via a call to `nix-gitignore`. I didn't apply this change to other derivations like `shell` or `package`, so if you're building those then #205 doesn't help you. But as I suggested then, I think it will work for most or all such cases.
