### ISSUE TITLE
Issue building a package with nodejs-8_x

### ISSUE THREAD

**Issue by eqyiel** [svanderburg/node2nix#94] opened 2018-06-17 20:00 UTC
After building this package with `node2nix` for ages, I've come across an issue when cooking it with the `--nodejs-8` flag.  Steps to reproduce:

```
git clone --recursive https://github.com/eqyiel/riot-electron-nix
cd riot-electron-nix
git submodule update # I don't remember if this is necessary after a recursive clone
git checkout nodejs-8_x-issue
nix-build --expr 'with import <nixpkgs> {}; callPackage ./default.nix { nodejs = pkgs.nodejs-8_x; }' --show-trace
```

Outcome:

```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/safer-buffer failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/nix-build-node-riot-web-0.15.5.drv-0/.npm/_logs/2018-06-17T19_52_43_671Z-debug.log
builder for '/nix/store/wc7l3xcgshiqgjihinv9xxj2v92gx5gc-node-riot-web-0.15.5.drv' failed with exit code 1
cannot build derivation '/nix/store/d2qbh5n7m4m9jqh3wr5mj0hw1kx0wpa6-riot-desktop-0.15.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d2qbh5n7m4m9jqh3wr5mj0hw1kx0wpa6-riot-desktop-0.15.5.drv' failed
```

`safer-buffer-2.1.2` exists in the sources though.

I suspected it might have something to do with [this line](https://github.com/eqyiel/riot-electron-nix/blob/nodejs-8_x-issue/node/generate.sh#L10), but I get the same result with or without it.

**Comment by eqyiel** [comment] 2018-06-17 20:04
In addition to that, I have issues building the master branch of that repo using a Node version other than the one it was cooked for (`--nodejs-6`):

```
$ # on master
$ nix-build --expr 'with import <nixpkgs> {}; callPackage ./default.nix { nodejs = pkgs.nodejs-8_x; }'
...
graceful-fs@4.1.11 /nix/store/3p17drch1ihmcan31mfbq71fdsibh5x9-node-riot-web-0.15.5/lib/node_modules/riot-web/node_modules/graceful-fs
npm ERR! code E404
npm ERR! 404 Not Found: auto-launch@5.0.5

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/nix-build-node-riot-web-0.15.5.drv-0/.npm/_logs/2018-06-17T20_02_32_085Z-debug.log
builder for '/nix/store/61ni4vx6nggri07422xifk2ziqdbqha4-node-riot-web-0.15.5.drv' failed with exit code 1
cannot build derivation '/nix/store/i6yc4ypyvgqsh9zzkny848yqga87jiwr-riot-desktop-0.15.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/i6yc4ypyvgqsh9zzkny848yqga87jiwr-riot-desktop-0.15.5.drv' failed
```

I think that might be expected behaviour though?

**Comment by svanderburg** [comment] 2018-06-20 14:06
I am not completely done yet with investigating this issue, but what I discovered so far is that if you generate expressions without the lock files, the deployments are failing because of missing peer dependencies.

This problem is caused by the fact that the packages seem to rely on old behaviour of NPM -- when a peer dependency is not a regular dependency, then it will be included automatically. This behaviour has changed in newer versions of NPM, and this is also the default behaviour in `node2nix`. In newer NPM versions, peer dependency declarations are just version checks -- they don't install the dependencies.

You can still simulate the old peer dependency behaviour by adding the `--include-peer-dependencies` option to `node2nix`. This seems to give me a successful deployment.

I have also tried the development version of `node2nix`, not the latest stable version.

**Comment by eqyiel** [comment] 2018-06-21 04:17
@svanderburg thanks for looking into it!

**Comment by svanderburg** [comment] 2018-11-28 16:33
I have now documented in the troubleshooting section of the README.md that for some packages the old behaviour needs to be emulated.

**Closed by svanderburg** 2018-11-28 16:33 UTC
