### ISSUE TITLE
Dev dependencies only at the top level

### ISSUE THREAD

**Issue by terlar** [svanderburg/node2nix#142] opened 2019-05-16 21:05 UTC
Now when you select `-d`/`--development` you seem to get all dev dependencies dev dependencies etc. Is there a way to only get the top level dev dependencies, e.g. those defined in the `package.json`?

**Comment by svanderburg** [comment] 2019-05-28 21:04
This should normally not be the case, otherwise an average project will be filled with thousands of dependencies. `node2nix` should only install development dependencies for the top-level packages and ignore transitive development dependencies.

Is there any example case you could provide me including the command-line instruction? Then I can investigate.

**Comment by svanderburg** [comment] 2020-03-11 10:47
Closing this, as I cannot reproduce this. If you run into a case in which you think the dependencies are wrong, can you reopen this and provide me an example config/CLI invocation?

**Closed by svanderburg** 2020-03-11 10:47 UTC

**Comment by terlar** [comment] 2020-03-11 16:56
@svanderburg Thank you, and sorry for not getting back on this. I wasn't working with nix together with node packages recently. Might work with it again, and will re-open if I experience the same thing again, with more details.
