### ISSUE TITLE
Build attempts network access on github dependencies

### ISSUE THREAD

**Issue by Ralith** [svanderburg/node2nix#122] opened 2018-12-07 19:46 UTC
Attempting to build https://github.com/vector-im/riot-web/tree/v0.17.7 using node2nix 1.6.0 output generated with
```
  --development \
  --nodejs-8 \
  --input node-packages.json \
  --composition default.nix \
  --node-env node-env.nix \
  --lock ../riot-web/package-lock.json
```
results in the Nix build attempting to run `git ls-remote -h -t ssh://git@github.com/matrix-org/gemini-scrollbar.git`. The dependency `"gemini-scrollbar": "github:matrix-org/gemini-scrollbar#b302279"` is specified in package.json. This normally fails with `ENOGIT`; if git is manually inserted into `globalBuildInputs`, then instead it fails with:
```
fatal: not a git repository: /nix/store/ddfpc731sndhb843i9yymvawdcbf7hgd-node-riot-web-0.17.7/lib/node_modules/riot-web/../.git/modules/riot-web
```
This seemed to be https://github.com/svanderburg/node2nix/issues/102, so I retried with riot-web downloaded as regular files instead of referenced as a submodule. Then, it instead fails with:
```
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.
```
as expected for a derivation that attempts to access the network illegally.

**Comment by msteen** [comment] 2019-01-03 18:16
I am running into this problem too while trying to package https://github.com/bitwarden/web. It has a dependency `git+https://github.com/duosecurity/duo_web_sdk.git` that fails due to lack of network access (if git is provided via `globalBuildInputs`).

**Comment by svanderburg** [comment] 2019-06-05 22:14
Can you check if this is still a problem with node2nix 1.7.0? Maybe this problem is caused by NPM dependencies that bundle package-lock.json files. The latest version contains a workaround for this.

**Comment by msteen** [comment] 2019-06-05 23:10
I just checked, with node2nix 1.7.0 this particular issue seems to be resolved as far as I have been able to test it. Unfortunately it now fails on another issue I encountered while packaging https://github.com/bitwarden/web under NixOS, namely `sh: opencollective: command not found`, but that should be unrelated to this particular issue, so I think the issue can be closed. Not sure though whether `opencollective postinstall` is common enough to be worth making a workaround for.

PS: In the case of https://github.com/bitwarden/web, I managed to package it as a fixed-output derivation and even that is no longer necessary because the author of `bitwarden_rs` now has a github repo containing prebuilt version of https://github.com/bitwarden/web, making packaging it for NixOS trivial.

**Comment by svanderburg** [comment] 2019-06-06 08:22
@msteen It looks like the problem you have encountered now is unrelated to the issue described here. Can you open a new issue for your problem?

**Comment by msteen** [comment] 2019-06-06 09:26
@svanderburg It indeed should be unrelated, as I mentioned. I opened #145 as requested.

**Comment by svanderburg** [comment] 2019-06-06 09:47
I'm closing this issue now, since the root cause of the package mentioned in the issue description has been solved.

**Closed by svanderburg** 2019-06-06 09:47 UTC
